name: Reviewdog
on: [pull_request]
jobs:
  credo:
    name: Credo
    runs-on: ubuntu-latest
    container:
      image: elixir:1.12-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: credo
        uses: yevh/reviewdog-action-credo@1d68a8bc263b3c09fc6db61641f4ba9aa0c3c027 #v1.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
