name: CredoAction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 9 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.12

      - name: Install Dependencies
        run: mix deps.get

      - name: Make script executable
        run: chmod +x ./scripts/credo_to_sarif.sh

      - name: Run Credo
        uses: yevh/credo-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload report
        uses: github/codeql-action/upload-sarif@d23060145bc9131d50558d5d4185494a20208101 #v2.12.5
        with:
          sarif_file: results.sarif
