name: CredoAction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 9 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  credo-check:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12'

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - id: run-action
        uses: yevh/credo-action@94ff9c9294824cc1f9a77532ddb8a12654562e1b  #1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload report
        uses: github/codeql-action/upload-sarif@d23060145bc9131d50558d5d4185494a20208101 #v2.12.5
        with:
          sarif_file: results.sarif
